name: soundpixel
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - cudatoolkit=10.2.89
  - ffmpeg=4.2.2
  - freetype=2.10.2
  - gmp=6.1.2
  - gnutls=3.6.5
  - intel-openmp=2020.2
  - jpeg=9b
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libvpx=1.7.0
  - lz4-c=1.9.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - nettle=3.4.1
  - ninja=1.10.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1g
  - pillow=7.2.0
  - pip=20.2.2
  - python=3.6.10
  - pytorch=1.6.0
  - readline=8.0
  - scipy=1.2.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchvision=0.7.0
  - wheel=0.35.1
  - x264=1!157.20191217
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - appdirs==1.4.4
    - audioread==2.1.8
    - cffi==1.14.2
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.2
    - future==0.18.2
    - idna==2.10
    - joblib==0.16.0
    - kiwisolver==1.2.0
    - librosa==0.8.0
    - llvmlite==0.34.0
    - matplotlib==3.3.1
    - mir-eval==0.6
    - numba==0.51.2
    - opencv-python==4.4.0.42
    - packaging==20.4
    - pandas==1.1.1
    - pooch==1.1.1
    - pycparser==2.20
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytube3==9.6.4
    - pytz==2020.1
    - requests==2.24.0
    - resampy==0.2.2
    - scikit-learn==0.23.2
    - soundfile==0.10.3.post1
    - threadpoolctl==2.1.0
    - torchaudio==0.6.0
    - typing-extensions==3.7.4.3
    - urllib3==1.25.10

